Repository AY2021S1-CS2103T-F11-4/tp, pull requests merged in 2020-10, with the labels that each got.

#113 Add use case labels and Update saving data use case
  docs/DeveloperGuide.md
Labels: type.Task

#115 Create walking skeleton
  src/main/java/seedu/address/model/country/Country.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/tag/TagFactory.java
  src/main/java/seedu/address/storage/JsonAdaptedCountry.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
Labels: type.Task

#119 Update command words to fit User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClientAddCommand.java
  src/main/java/seedu/address/logic/commands/ClientDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ClientEditCommand.java
  src/main/java/seedu/address/logic/commands/ClientFindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientFindCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClientAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientFindCommandParserTest.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
Labels: priority.High, type.Task

#118 Country implementation
  src/main/java/seedu/address/model/country/Country.java
  src/main/java/seedu/address/model/country/CountryManager.java
  src/test/java/seedu/address/model/country/CountryManagerTest.java
  src/test/java/seedu/address/model/country/CountryTest.java
  src/test/java/seedu/address/model/country/NoteStub.java
Labels: priority.High, type.Task

#117 Update help window contents
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#121 Country filter v1
  src/main/java/seedu/address/logic/commands/ClientFindCommand.java
  src/main/java/seedu/address/logic/commands/CountryFilterCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CountryFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/CountryNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/ClientCountryMatchesInputCountryPredicate.java
  src/main/java/seedu/address/model/country/Country.java
  src/main/java/seedu/address/model/country/CountryManager.java
  src/main/java/seedu/address/model/note/Note.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CountryFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/CountryFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/CountryMatchesInputCountryPredicateTest.java
  src/test/java/seedu/address/model/country/CountryManagerTest.java
  src/test/java/seedu/address/model/country/CountryTest.java
  src/test/java/seedu/address/model/country/NoteStub.java
Labels: priority.High, type.Story

#133 Allow user to close help window with Esc key
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task

#125 View Command Implementation and model interaction
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClientViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClientViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/widget/WidgetModel.java
  src/main/java/seedu/address/model/widget/WidgetModelManager.java
  src/main/java/seedu/address/model/widget/WidgetObject.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/main/resources/images/TBM.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WidgetViewBox.fxml
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClientViewCommandParserTest.java
  src/test/java/seedu/address/model/widget/WidgetObjectTest.java
Labels: priority.High, type.Task

#135 Create new workflow that automatically generates and commits UML pngs
  .github/workflows/plantuml.yml
Labels: type.Admin

#136 Add PR template file
  .github/pull_request_template.md
Labels: type.Admin

#138 Updates to puml diagram
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.Low, severity.Low

#141 Update plantuml.yml
  .github/workflows/plantuml.yml
Labels: type.Bug

#142 Update user feedback messages for Country Filter
  src/main/java/seedu/address/logic/commands/CountryFilterCommand.java
  src/main/java/seedu/address/logic/parser/CountryFilterCommandParser.java
  src/main/java/seedu/address/model/client/ClientCountryMatchesInputCountryPredicate.java
  src/main/java/seedu/address/model/country/Country.java
Labels: priority.Medium, severity.VeryLow

#143 Update user feedback messages for Country Note
  src/main/java/seedu/address/logic/commands/CountryNoteCommand.java
  src/main/java/seedu/address/logic/parser/CountryNoteCommandParser.java
Labels: priority.Medium, severity.VeryLow

#144 Add tests for Country Filter and Country Note related files
  src/main/java/seedu/address/model/country/Country.java
  src/main/java/seedu/address/model/country/CountryManager.java
  src/test/java/seedu/address/logic/commands/CountryFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/CountryFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteCommandParserTest.java
  src/test/java/seedu/address/model/client/ClientCountryMatchesInputCountryPredicateTest.java
  src/test/java/seedu/address/model/client/CountryMatchesInputCountryPredicateTest.java
  src/test/java/seedu/address/model/country/CountryManagerTest.java
  src/test/java/seedu/address/model/country/CountryTest.java
Labels: priority.Medium

#147 Update UG for country note and country filter
  docs/UserGuide.md
Labels: severity.VeryLow, type.documentation

#149 Implement a unique tag set
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/tag/TagFactory.java
  src/main/java/seedu/address/model/tag/UniqueTagSet.java
  src/test/java/seedu/address/model/tag/UniqueTagSetTest.java
Labels: priority.High, type.Task

#146 Add test for viewcommand
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/widget/WidgetModel.java
  src/main/java/seedu/address/model/widget/WidgetModelManager.java
  src/main/java/seedu/address/model/widget/WidgetObject.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/test/java/seedu/address/model/widget/WidgetModelManagerTest.java
  src/test/java/seedu/address/model/widget/WidgetObjectTest.java
Labels: priority.Medium, severity.Low

#148 Update country code to be non-optional param
  docs/UserGuide.md
Labels: type.documentation

#151 Refactor country notes to CountryManager
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/country/Country.java
  src/main/java/seedu/address/model/country/CountryManager.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/test/java/seedu/address/logic/parser/ClientAddCommandParserTest.java
  src/test/java/seedu/address/model/country/CountryManagerTest.java
  src/test/java/seedu/address/model/country/CountryTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
Labels: type.Enhancement, type.Task

#153 Remove all trailing whitespace
  .github/pull_request_template.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/leeenhao.md
Labels: type.Task

#139 Update tests to include country and timezone
  src/main/java/seedu/address/logic/commands/ClientEditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClientDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientFindCommandParser.java
  src/test/java/seedu/address/logic/parser/ClientAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/TimezoneTest.java
Labels: type.Task

#155 Update UserGuide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClientAddCommand.java
  src/main/java/seedu/address/logic/commands/ClientEditCommand.java
Labels: type.documentation

#158 Add Portfolio updates for v1.2
  docs/UserGuide.md
  docs/team/leeenhao.md
  docs/team/qwoprocks.md
  docs/team/raysonkoh.md
  docs/team/rtshkmr.md
  docs/team/tankangliang.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.documentation

#159 Update README.md
  README.md
Labels: type.Admin

#161 Increase test coverage
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: type.Task

#150 Add TagNoteMap implementation
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClientNoteAddCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClientNoteAddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/country/CountryManager.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/note/TagNoteMap.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClientNoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientNoteAddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/note/NoteTest.java
  src/test/java/seedu/address/model/note/TagNoteMapTest.java
Labels: priority.High

#195 Enable assertions in build.gradle
  build.gradle
Labels: type.Admin

#191 Add contract expiry field to client
  src/main/java/seedu/address/logic/commands/ClientAddCommand.java
  src/main/java/seedu/address/logic/commands/ClientEditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ClientAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientEditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/ContractExpiryDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ClientAddCommandParserTest.java
  src/test/java/seedu/address/model/client/ContractExpiryDateTest.java
  src/test/java/seedu/address/model/client/TimezoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: priority.High, type.Task

#199 Add implementation for suggest available
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/logic/parser/SuggestCommandParser.java
  src/main/java/seedu/address/model/client/SuggestAvailabilityPredicate.java
  src/main/java/seedu/address/model/client/SuggestionType.java
  src/main/java/seedu/address/model/client/Timezone.java
  src/test/java/seedu/address/model/client/SuggestAvailabilityPredicateTest.java
  src/test/java/seedu/address/model/client/SuggestionTypeTest.java
  src/test/java/seedu/address/model/client/TimezoneTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
Labels: priority.High

#204 Update DG implementation section for suggest command
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SuggestSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SuggestSequenceDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/note/TagNoteMap.java
Labels: type.documentation

#205 Branch timezone fix
  build.gradle
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Timezone.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/client/AddressTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/EmailTest.java
  src/test/java/seedu/address/model/client/NameTest.java
  src/test/java/seedu/address/model/client/PhoneTest.java
  src/test/java/seedu/address/model/client/TimezoneTest.java
  src/test/java/seedu/address/model/country/CountryManagerTest.java
  src/test/java/seedu/address/model/note/NoteTest.java
  src/test/java/seedu/address/testutil/ClientUtil.java
Labels: priority.Medium, type.Bug

#198 Store country notes json
  src/main/java/seedu/address/logic/commands/CountryNoteCommand.java
  src/main/java/seedu/address/logic/parser/CountryNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/country/Country.java
  src/main/java/seedu/address/model/country/CountryCodeVerifier.java
  src/main/java/seedu/address/model/country/CountryManager.java
  src/main/java/seedu/address/model/country/CountryNotesManager.java
  src/main/java/seedu/address/model/note/CountryNote.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClientAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/country/CountryCodeVerifierTest.java
  src/test/java/seedu/address/model/country/CountryManagerTest.java
  src/test/java/seedu/address/model/country/CountryNotesManagerTest.java
  src/test/java/seedu/address/model/country/NoteStub.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedNoteTest.java
Labels: priority.High

#206 Increase logic test coverage
  docs/diagrams/SuggestSequenceDiagram.puml
  docs/images/SuggestSequenceDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClientNoteAddCommand.java
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/logic/parser/ClientNoteAddCommandParser.java
  src/main/java/seedu/address/logic/parser/SuggestCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/SuggestCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientNoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SuggestCommandParserTest.java
Labels: type.Task

#196 Update DG to reflect model changes
  docs/DeveloperGuide.md
  docs/diagrams/InnerWorkings.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/InnerWorkings.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: priority.High

#207 Add diagrams to developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SuggestActivityDiagram.puml
  docs/diagrams/SuggestState0.puml
  docs/diagrams/SuggestState1.puml
  docs/diagrams/SuggestState2.puml
  docs/images/ModelClassDiagram.png
  docs/images/SuggestActivityDiagram.png
  docs/images/SuggestState0.png
  docs/images/SuggestState1.png
  docs/images/SuggestState2.png
Labels: type.documentation

#212 Add minor DG update
  docs/DeveloperGuide.md
  docs/diagrams/TagNoteMapSequence.puml
  docs/images/TagNoteMapSequence.png
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
Labels: type.documentation

#203 Client Notes: Deleting Client Notes
  src/main/java/seedu/address/logic/commands/ClientNoteDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClientNoteDeleteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/note/TagNoteMap.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WidgetViewBox.fxml
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClientNoteDeleteCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/note/TagNoteMapTest.java
Labels: WIP, priority.High

#215 Country note view
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClientViewCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CountryFilterCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteViewCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CountryNoteViewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/country/CountryNotesManager.java
  src/main/java/seedu/address/model/widget/WidgetModelManager.java
  src/main/java/seedu/address/model/widget/WidgetObject.java
  src/main/java/seedu/address/ui/CountryNoteCard.java
  src/main/java/seedu/address/ui/CountryNoteListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WidgetViewOption.java
  src/main/resources/view/CountryNoteCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/WidgetListViewBox.fxml
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteViewCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteViewCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/country/CountryNotesManagerTest.java
  src/test/java/seedu/address/model/country/CountryTest.java
  src/test/java/seedu/address/model/note/CountryNoteTest.java
Labels: priority.High

#216 Add testing for Notes
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/logic/commands/ClientNoteAddCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteViewCommand.java
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CountryNoteViewCommandParser.java
  src/main/java/seedu/address/logic/parser/SuggestCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/SuggestionType.java
  src/main/java/seedu/address/model/client/Timezone.java
  src/main/java/seedu/address/model/country/CountryNotesManager.java
  src/main/java/seedu/address/model/note/TagNoteMap.java
  src/main/java/seedu/address/model/widget/WidgetModelManager.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClientAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientNoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientNoteDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/SuggestionTypeTest.java
  src/test/java/seedu/address/model/client/TimezoneTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
  src/test/java/seedu/address/model/country/CountryNotesManagerTest.java
  src/test/java/seedu/address/model/note/TagNoteMapTest.java
  src/test/java/seedu/address/model/widget/WidgetObjectTest.java
  src/test/java/seedu/address/testutil/ClientUtil.java
Labels: type.Testing

#221 Make contract expiry date optional and implement client list sorting
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClientAddCommand.java
  src/main/java/seedu/address/logic/commands/ClientDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ClientEditCommand.java
  src/main/java/seedu/address/logic/commands/ClientFindCommand.java
  src/main/java/seedu/address/logic/commands/ClientNoteAddCommand.java
  src/main/java/seedu/address/logic/commands/ClientNoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ClientViewCommand.java
  src/main/java/seedu/address/logic/commands/CountryFilterCommand.java
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/logic/parser/ClientAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SuggestCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/ContractExpiryDate.java
  src/main/java/seedu/address/model/client/LastModifiedInstant.java
  src/main/java/seedu/address/model/client/SuggestContractPredicate.java
  src/main/java/seedu/address/model/client/SuggestionType.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientFindCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientViewCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CountryFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/SuggestCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SuggestCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/LastModifiedInstantTest.java
  src/test/java/seedu/address/model/client/SuggestContractPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: type.Task

#223 Country note delete
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ClientViewCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CountryNoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CountryFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/CountryNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/CountryNoteDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/CountryNoteViewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/country/Country.java
  src/main/java/seedu/address/model/country/CountryNotesManager.java
  src/main/java/seedu/address/model/note/CountryNote.java
  src/main/java/seedu/address/ui/CountryNoteCard.java
  src/main/java/seedu/address/ui/CountryNoteListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WidgetViewOption.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CountryFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteViewCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/country/CountryNotesManagerTest.java
  src/test/java/seedu/address/ui/WidgetViewOptionTest.java
Labels: priority.Medium, type.Story

#197 GUI test and systems test suites
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  docs/Testing.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/ClientViewCommand.java
  src/main/java/seedu/address/model/widget/WidgetObject.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/TextClock.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/main/resources/view/CountryNoteCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WidgetListViewBox.fxml
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/ClientCardHandle.java
  src/test/java/guitests/guihandles/ClientListPanelHandle.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/CountryNoteCardHandle.java
  src/test/java/guitests/guihandles/CountryNoteListPanelHandle.java
  src/test/java/guitests/guihandles/HelpWindowHandle.java
  src/test/java/guitests/guihandles/MainMenuHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/NodeHandle.java
  src/test/java/guitests/guihandles/ResultDisplayHandle.java
  src/test/java/guitests/guihandles/StageHandle.java
  src/test/java/guitests/guihandles/StatusBarFooterHandle.java
  src/test/java/guitests/guihandles/WidgetViewBoxHandle.java
  src/test/java/guitests/guihandles/exceptions/NodeNotFoundException.java
  src/test/java/guitests/guihandles/exceptions/StageNotFoundException.java
  src/test/java/seedu/address/model/widget/WidgetObjectTest.java
  src/test/java/seedu/address/ui/ClientCardTest.java
  src/test/java/seedu/address/ui/ClientListPanelTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/CountryNoteCardTest.java
  src/test/java/seedu/address/ui/CountryNoteListPanelTest.java
  src/test/java/seedu/address/ui/GuiUnitTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/MainWindowTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/seedu/address/ui/WidgetViewBoxTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/seedu/address/ui/testutil/StageExtension.java
  src/test/java/seedu/address/ui/testutil/UiPartExtension.java
Labels: priority.High, severity.Medium, type.Testing

#237 Add parsing logic for country note [add | delete | view]
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CountryNoteAddCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CountryNoteAddCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/CountryNoteAddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteAddCommandParserTest.java
Labels: priority.Medium, type.Task

#220 Minor CSS tweaks
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/images/TBM.png
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/ui/ResultDisplayTest.java
Labels: priority.Medium, severity.Low, type.Task

#235 Note: Implement Storage & Store as JSON
  docs/UserGuide.md
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedNoteTest.java
Labels: priority.High

#247 Update note card and other CSS
  src/main/java/seedu/address/logic/parser/CountryNoteAddCommandParser.java
  src/main/java/seedu/address/model/country/CountryNotesManager.java
  src/main/java/seedu/address/model/note/CountryNote.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/ui/ClientListCard.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/CountryNoteCard.java
  src/main/java/seedu/address/ui/CountryNoteListPanel.java
  src/main/java/seedu/address/ui/NoteListCard.java
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/CountryNoteCard.fxml
  src/main/resources/view/CountryNoteListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NoteListCard.fxml
  src/main/resources/view/WidgetListViewBox.fxml
  src/test/java/guitests/guihandles/CountryNoteCardHandle.java
  src/test/java/guitests/guihandles/CountryNoteListPanelHandle.java
  src/test/java/guitests/guihandles/NoteListCardHandle.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/ui/ClientListCardTest.java
  src/test/java/seedu/address/ui/CountryNoteCardTest.java
  src/test/java/seedu/address/ui/CountryNoteListPanelTest.java
  src/test/java/seedu/address/ui/NoteListCardTest.java
Labels: priority.High, type.Task

#249 Remove client tags and add more tests for parsing
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClientAddCommand.java
  src/main/java/seedu/address/logic/commands/ClientEditCommand.java
  src/main/java/seedu/address/logic/parser/ClientAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientEditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/widget/WidgetModelManager.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientListCard.java
  src/main/resources/view/ClientListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/guitests/guihandles/ClientCardHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClientAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClientNoteAddCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/model/widget/WidgetModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
  src/test/java/seedu/address/ui/ClientListCardTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.High

#251 Add tests for commons and logic
  src/main/java/seedu/address/commons/util/PairUtil.java
  src/main/java/seedu/address/logic/commands/CountryFilterCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteViewCommand.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientAddCommandParserTest.java
  src/test/java/seedu/address/model/client/SuggestAvailabilityPredicateTest.java
  src/test/java/seedu/address/model/client/SuggestionTypeTest.java
Labels: priority.Medium

#255 Client Notes: Fix Indexing Bug
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClientNoteDeleteCommand.java
  src/main/java/seedu/address/model/client/Client.java
  src/test/java/seedu/address/logic/commands/ClientNoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientNoteDeleteCommandParserTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
Labels: priority.High, severity.High

#257 UserGuide update
  docs/UserGuide.md
Labels: type.documentation

#258 Increase test coverage for model package
  build.gradle
  src/main/java/seedu/address/model/TbmManager.java
  src/main/java/seedu/address/model/country/CountryNotesManager.java
  src/test/java/seedu/address/model/TbmManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/country/CountryCodeVerifierTest.java
  src/test/java/seedu/address/model/country/CountryNotesManagerTest.java
  src/test/java/seedu/address/model/country/CountryTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/tag/UniqueTagSetTest.java
Labels: priority.Medium, type.Task, type.Testing

#245 Update DG for CountryNotesManager
  docs/DeveloperGuide.md
  docs/diagrams/CountryClass.puml
  docs/diagrams/CountryNoteAddSeqDiag.puml
  docs/images/CountryClass.png
  docs/images/CountryNoteAddSeqDiag.png
Labels: type.documentation

#244 Add tags field to country note add
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClientNoteAddCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteAddCommand.java
  src/main/java/seedu/address/logic/parser/CountryNoteAddCommandParser.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/CountryNoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
Labels: priority.Medium

#259 Client Notes: Update feature
  src/main/java/seedu/address/logic/commands/ClientNoteEditCommand.java
  src/main/java/seedu/address/logic/parser/ClientNoteEditCommandParser.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/note/TagNoteMap.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteEditCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientNoteEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/note/TagNoteMapTest.java
Labels: priority.High

#267 Fix certain bugs in country notes list
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CountryNoteDeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/country/CountryNotesManager.java
  src/main/java/seedu/address/model/note/CountryNote.java
  src/main/java/seedu/address/ui/CountryNoteListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteDeleteCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/country/CountryNotesManagerTest.java
Labels: severity.Medium, type.Bug, type.Task

#266 Country note update
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CountryNoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteEditCommand.java
  src/main/java/seedu/address/logic/parser/CountryNoteEditCommandParser.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TbmManager.java
  src/main/java/seedu/address/model/country/CountryNotesManager.java
  src/main/java/seedu/address/model/note/CountryNote.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteEditCommandTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
  src/test/java/seedu/address/model/country/CountryNotesManagerTest.java
  src/test/java/seedu/address/model/note/CountryNoteTest.java
Labels: priority.High, type.Task

#274 Fix country note list ordering
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/country/Country.java
  src/main/java/seedu/address/model/note/CountryNote.java
Labels: severity.Medium, type.Bug, type.Task

#256 Gui
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClientViewCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/widget/WidgetModel.java
  src/main/java/seedu/address/model/widget/WidgetModelManager.java
  src/main/java/seedu/address/model/widget/WidgetObject.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/WidgetViewBox.fxml
  src/test/java/guitests/guihandles/CountryNoteListPanelHandle.java
  src/test/java/guitests/guihandles/NoteListCardHandle.java
  src/test/java/guitests/guihandles/WidgetViewBoxHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientViewCommandTest.java
  src/test/java/seedu/address/model/widget/WidgetModelManagerTest.java
  src/test/java/seedu/address/model/widget/WidgetObjectTest.java
  src/test/java/seedu/address/ui/MainWindowTest.java
  src/test/java/seedu/address/ui/WidgetViewBoxTest.java
Labels: priority.High

#268 Client Edit, Client Note Edit Bug Fixes
  src/main/java/seedu/address/logic/commands/ClientEditCommand.java
  src/main/java/seedu/address/logic/commands/ClientNoteEditCommand.java
  src/main/java/seedu/address/logic/parser/ClientNoteEditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TbmManager.java
  src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteEditCommandTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: priority.High

#240 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/TBM_BRAND.png
  src/main/java/seedu/address/logic/commands/ClientFindCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.documentation

#276 Add relevant screenshots to UG
  README.md
  docs/UserGuide.md
  docs/images/UI.png
  docs/images/Ui_old.png
  docs/images/command-screenshots/UI_annotated.png
  docs/images/command-screenshots/client_note_edit_before.png
  docs/images/command-screenshots/client_view.png
  docs/images/command-screenshots/client_view_annotated.png
  docs/images/command-screenshots/country_note_add.png
  docs/images/command-screenshots/country_note_edit_after_resultBox.png
  docs/images/command-screenshots/country_note_edit_before.png
  docs/images/command-screenshots/country_note_view.png
  docs/images/command-screenshots/country_note_view_annotated.png
  docs/images/command-screenshots/help_window.png
  docs/images/command-screenshots/result_display_error_syntax.png
  docs/index.md
  docs/team/leeenhao.md
  docs/team/qwoprocks.md
  docs/team/raysonkoh.md
  docs/team/rtshkmr.md
  docs/team/tankangliang.md
Labels: priority.Medium, type.documentation

#312 Fix Ordering Bug for ClientNoteEdit
  src/main/java/seedu/address/logic/commands/ClientEditCommand.java
  src/main/java/seedu/address/logic/commands/ClientNoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ClientNoteEditCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TbmManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/note/TagNoteMap.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/test/java/seedu/address/logic/commands/ClientNoteEditCommandTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/note/TagNoteMapTest.java
  src/test/java/seedu/address/ui/MainWindowTest.java
Labels: priority.High, type.Bug

#317 Fix dry run bugs
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClientViewCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CountryNoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteEditCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteViewCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CountryNoteListPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TextClock.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/main/resources/images/TBM_transparent.png
  src/main/resources/view/CountryNoteListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NoteListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/WidgetViewBox.fxml
  src/test/java/guitests/guihandles/WidgetViewBoxHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/SuggestCommandTest.java
  src/test/java/seedu/address/ui/MainWindowTest.java
  src/test/java/seedu/address/ui/WidgetViewBoxTest.java
Labels: priority.High, severity.High, type.Bug

#314 Fix bug in clear cmd for country notes
  src/main/java/seedu/address/model/TbmManager.java
  src/main/java/seedu/address/model/country/CountryNotesManager.java
Labels: severity.High, type.Bug
