Repository AY2021S1-CS2103T-F11-4/tp, pull requests merged in 2020-11, with the labels that each got.

#252 Command history for CLI
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandHistory.java
  src/main/resources/view/CommandBox.fxml
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/CommandHistoryTest.java
Labels: priority.Medium, severity.Low

#320 Standardise Storage and Loading Order for Client Notes
  src/main/java/seedu/address/model/ReadOnlyTbmManager.java
  src/main/java/seedu/address/model/TbmManager.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonSerializableTbmManager.java
  src/test/data/JsonSerializableTbmManagerTest/duplicateClientTbmManager.json
  src/test/data/JsonSerializableTbmManagerTest/invalidClientTbmManager.json
  src/test/data/JsonSerializableTbmManagerTest/typicalClientsTbmManager.json
  src/test/data/JsonTbmManagerStorageTest/invalidClientTbmManager.json
  src/test/java/seedu/address/model/TbmManagerTest.java
  src/test/java/seedu/address/storage/JsonSerializableTbmManagerTest.java
  src/test/java/seedu/address/ui/MainWindowTest.java
Labels: priority.Medium, severity.Medium

#321 Add sample country notes
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Task

#335 Country note delete and country note edit fix
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClientNoteEditCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteEditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClientAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ClientNoteEditCommandTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteEditCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, severity.High, type.Bug

#334 Add glossary from DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation

#322 Country note UG update
  docs/UserGuide.md
Labels: type.documentation

#336 Minor Fixes from Dry Run
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ClientFindCommand.java
  src/test/java/seedu/address/commons/core/MessagesTest.java
  src/test/java/seedu/address/logic/commands/ClientFindCommandTest.java
Labels: type.Bug, type.documentation

#333 Organise UG pictures, Add figure caption
  docs/UserGuide.md
Labels: type.documentation

#331 Fixes for dry run bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/model/note/NoteTest.java
  src/test/java/seedu/address/storage/JsonAdaptedNoteTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task

#338 UserGuide edits based on comments
  docs/UserGuide.md
Labels: priority.Medium, type.documentation

#339 Update tests for tagNoteMap
  src/main/java/seedu/address/model/note/TagNoteMap.java
  src/test/java/seedu/address/model/note/TagNoteMapTest.java
Labels: type.Testing

#337 Hotline Bling
  docs/UserGuide.md
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/model/tag/UniqueTagSet.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/PhoneTest.java
  src/test/java/seedu/address/model/tag/UniqueTagSetTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
Labels: priority.High, type.Bug

#341 Add note that prefixes are special keywords
  docs/UserGuide.md
Labels: type.documentation

#330 Fixes for dry run comments
  src/main/java/seedu/address/logic/commands/ClientListCommand.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/test/java/guitests/guihandles/WidgetViewBoxHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClientListCommandTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#344 Minor markdown rendering
  docs/UserGuide.md
Labels: type.documentation

#340 Display time in client's current timezone in client view
  src/main/java/seedu/address/model/client/Timezone.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/TextClock.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/main/resources/view/WidgetViewBox.fxml
  src/test/java/seedu/address/model/client/TimezoneTest.java
Labels: type.Enhancement

#345 [Storage Package] Code Quality Improvements
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonSerializableTbmManager.java
  src/main/java/seedu/address/storage/JsonTbmManagerStorage.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedNoteTest.java
  src/test/java/seedu/address/storage/JsonSerializableTbmManagerTest.java
  src/test/java/seedu/address/storage/JsonTbmManagerStorageTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.Medium, type.Task

#323 Country note DG update
  docs/DeveloperGuide.md
  docs/diagrams/CountryClass.puml
  docs/diagrams/CountryNoteAddSeqDiag.puml
  docs/diagrams/CountryNotePanelClientViewActDiag.puml
  docs/images/CountryClass.png
  docs/images/CountryNoteAddSeqDiag.png
  docs/images/CountryNotePanelClientViewActDiag.png
Labels: type.documentation

#342 Fix code quality in [client, country, note, tag] packages
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TbmManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Name.java
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/country/Country.java
  src/main/java/seedu/address/model/country/CountryCodeVerifier.java
  src/main/java/seedu/address/model/country/CountryNotesManager.java
  src/main/java/seedu/address/model/note/CountryNote.java
  src/main/java/seedu/address/model/note/TagNoteMap.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task

#349 Add back other os to ci
  .github/workflows/gradle.yml
  src/main/java/seedu/address/ui/WidgetViewBox.java
Labels: type.Admin

#352 Bound window width height position
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/test/java/seedu/address/ui/MainWindowTest.java
Labels: severity.Medium, type.Bug

#346 Make ClientNoteEdit command accept either tags or note string or both
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ClientNoteEditCommand.java
  src/main/java/seedu/address/logic/parser/ClientNoteEditCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/ClientNoteEditCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientNoteEditCommandParserTest.java
Labels: priority.Medium, type.Bug, type.Enhancement

#355 Update suggest command description
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/model/client/SuggestionType.java
  src/test/java/guitests/guihandles/WidgetViewBoxHandle.java
  src/test/java/seedu/address/logic/commands/SuggestCommandTest.java
  src/test/java/seedu/address/model/client/SuggestionTypeTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/CountryNoteListPanelTest.java
  src/test/java/seedu/address/ui/MainWindowTest.java
  src/test/java/seedu/address/ui/WidgetViewBoxTest.java
Labels: type.Task

#358 Fix bug in country/client note edit duplicate note
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClientNoteEditCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteEditCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/test/java/seedu/address/logic/commands/ClientNoteEditCommandTest.java
  src/test/java/seedu/address/logic/parser/CountryNoteEditCommandParserTest.java
Labels: severity.High, type.Bug

#357 Change suggest to client suggest
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClientSuggestCommand.java
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/logic/parser/ClientSuggestCommandParser.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SuggestCommandParser.java
  src/main/java/seedu/address/model/client/ClientSuggestAvailabilityPredicate.java
  src/main/java/seedu/address/model/client/ClientSuggestContractPredicate.java
  src/main/java/seedu/address/model/client/ClientSuggestionType.java
  src/test/java/seedu/address/logic/commands/ClientSuggestCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientClientSuggestCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SuggestCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/ClientSuggestAvailabilityPredicateTest.java
  src/test/java/seedu/address/model/client/ClientSuggestContractPredicateTest.java
  src/test/java/seedu/address/model/client/ClientSuggestionTypeTest.java
  src/test/java/seedu/address/model/client/SuggestionTypeTest.java
Labels: priority.Medium, type.Task

#362 Fix code quality for logic package
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClientAddCommand.java
  src/main/java/seedu/address/logic/commands/ClientDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ClientEditCommand.java
  src/main/java/seedu/address/logic/commands/ClientFindCommand.java
  src/main/java/seedu/address/logic/commands/ClientNoteAddCommand.java
  src/main/java/seedu/address/logic/commands/ClientNoteEditCommand.java
  src/main/java/seedu/address/logic/commands/ClientSuggestCommand.java
  src/main/java/seedu/address/logic/commands/ClientViewCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CountryNoteAddCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteEditCommand.java
  src/main/java/seedu/address/logic/commands/CountryNoteViewCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ClientAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientEditCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientFindCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientNoteAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientNoteDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientNoteEditCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientSuggestCommandParser.java
  src/main/java/seedu/address/logic/parser/ClientViewCommandParser.java
  src/main/java/seedu/address/logic/parser/CountryFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/CountryNoteAddCommandParser.java
  src/main/java/seedu/address/logic/parser/CountryNoteDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/CountryNoteEditCommandParser.java
  src/main/java/seedu/address/logic/parser/CountryNoteViewCommandParser.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ClientDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CountryNoteDeleteCommandTest.java
Labels: priority.High, type.Task

#354 Change timezone to only accept valid timezones
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClientAddCommand.java
  src/main/java/seedu/address/model/client/ClientSuggestionType.java
  src/main/java/seedu/address/model/client/Timezone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
  src/test/data/JsonSerializableTbmManagerTest/duplicateClientTbmManager.json
  src/test/data/JsonSerializableTbmManagerTest/typicalClientsTbmManager.json
  src/test/data/JsonTbmManagerStorageTest/invalidAndValidClientTbmManager.json
  src/test/data/JsonTbmManagerStorageTest/invalidClientTbmManager.json
  src/test/java/seedu/address/logic/commands/ClientAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/ClientSuggestAvailabilityPredicateTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/TimezoneTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
  src/test/java/seedu/address/ui/MainWindowTest.java
Labels: priority.High

#332 PPP - Rayson
  docs/team/raysonkoh.md
Labels: type.Admin

#360 Sample and commons package
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/commons/core/Version.java
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/WidgetViewBox.java
Labels: priority.High
