Repository AY2021S1-CS2103T-F11-4/tp, pull requests merged in 2020-09, with the labels that each got.

#30 Update site wide settings and index.md
  docs/_config.yml
  docs/index.md
Labels: documentation, type.Task

#31 Move “Adding Country Notes”, “Clearing All Entries” and “Exiting the Program” sections to UserGuide.md
  docs/AboutUs.md
  docs/UserGuide.md
Labels: documentation, type.Task

#32 Update AboutUs with Rayson's information
  docs/AboutUs.md
  docs/images/raysonkoh.png
  docs/team/raysonkoh.md
Labels: documentation, type.Admin, type.Task

#38 Add list of user stories to the Developer Guide
  docs/DeveloperGuide.md
Labels: documentation, type.Task

#40 Update link of github build status badge to point to team repo
  README.md
Labels: documentation, type.Task

#39 Update AboutUs with MC's information
  docs/AboutUs.md
  docs/team/qwoprocks.md
Labels: documentation, type.Admin, type.Task

#45 Add Saving Data use case to DG
  docs/DeveloperGuide.md
Labels: documentation, type.Task

#42 Add “Deleting clients”, “Saving Data”, “Adding Notes” to UG
  docs/UserGuide.md
Labels: documentation, type.Task

#46 Add Non-Functional Requirements section to DG
  docs/DeveloperGuide.md
Labels: documentation, type.Task

#59 Update AboutUs: Add MC profile photo (placeholder image)
  docs/AboutUs.md
  docs/images/qwoprocks.png
Labels: documentation

#53 Update DeveloperGuide.md with `clearing all entries` use case documentation
  docs/DeveloperGuide.md
Labels: documentation, type.Story, type.Task

#61 AboutUs Update: Add Kang Liang's details
  docs/AboutUs.md
  docs/images/tankangliang.png
  docs/team/tankangliang.md
Labels: documentation

#62 UG Update: Move “Deleting notes”, “Updating client notes” and “Filtering by country” sections
  docs/UserGuide.md
Labels: documentation

#65 DG Update: Add “Filtering by country” to use cases
  docs/DeveloperGuide.md
Labels: documentation

#63 README Update: Acknowledge original source of code
  README.md
Labels: documentation

#64 DG Update: Glossary
  docs/DeveloperGuide.md
Labels: documentation

#70 Update Dev guide; Add TBM welcome in User guide; Update responsibilities in AboutUs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/TBM.png
Labels: documentation, type.Task

#71 Maindocs
  docs/DeveloperGuide.md
  docs/images/Ui.png
  docs/images/Ui.psd
Labels: type.Task

#73 Update TOC for DG,UG & minor touchups
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, type.Admin
